### ISSUE TITLE
[Blog] Create a forum system with Node.js and React, and add Novu.

### ISSUE THREAD

**Issue by nevo-david** [novuhq/blog#2]
# Thank you for taking part in Hacktoberfest!
Here you can find details and guidelines to submit a blog post during Hacktoberfest that will be featured on our website and dev. to.

Once this issue is assigned, it will move to the Blog Repository
https://github.com/novuhq/blog/

### Achievements 
1. List in our [Community Heroes](https://novu.co/contributors) page with a "Writer" badge.
2. Get swag!

### How To Start:

1. Clone [this](https://github.com/novuhq/blog/) repository to your computer and create a new folder called **novu-forum-system**
3. Inside the new folder, create a new file called Blog.md - where you will write your blog post details.
4. Create two new folders: client/backend, and write the article source code inside them.
5. TIP! Start writing to source code before writing the blog post.

### What should you write about?

1. Create a basic forum system with Node.js (express) and React: Registration, Login, and create a new post and comments.
2. Each time there is a new comment in a post, send notifications using Novu for all the post participants via the notification center.
3. BONUS: add a like button for each comment and send a notification on a new like to the comment owner.

Good Luck!

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue

**Comment by nevo-david** [comment]
No problem! Let's go :)

**Comment by nevo-david** [comment]
Hi @AnshuPathak-88825, just following up on this :)

**Comment by oneknucklehead** [comment]
Is this issue still up? can i work on this?
