### ISSUE TITLE
chat-app-reactnative-socketIO

### ISSUE THREAD

**Issue by smhj1003** [novuhq/blog#4]
Hello
I proceeded by referring to the corresponding Repo and blog. 

Network request failed
at node_modules/whatwg-fetch/dist/fetch.umd.js:535:30 in setTimeout$argument_0
![image](https://user-images.githubusercontent.com/57647004/207011769-2207b751-1ec5-454e-9a31-10ae0ed437d5.png)

I faced this problem.  What's the problem?

**Comment by dha-stix** [comment]
Hi @smhj1003 

This comment here might be helpful: https://dev.to/jterranova/comment/2370f
The project was built using Xcode (IOS Emulator) which is the cause of the error on Android.
